apiVersion: apps/v1
kind: Deployment
metadata:
  name: okteto-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: okteto-test
  template:
    metadata:
      labels:
        app: okteto-test
    spec:
      imagePullSecrets:
      - name: mysecretname  
      terminationGracePeriodSeconds: 0
      containers:
      - name: okteto
        image: docker.pkg.github.com/lcastils/okteto/okteto-image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: okteto-test
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: okteto-test
spec:
  type: ClusterIP
  ports:
    - name: okteto-test
      port: 8080
  selector:
    app: okteto-test